spring:
  datasource:
    druid:
      stat-view-servlet:
#        loginUsername: admin
#        loginPassword: 123456
        reset-enable: false
    dynamic:
      primary: master
      p6sy: true # 默认false,建议线上关闭
      druid: 
        initial-size: 1
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: false
        filters: stat,wall, slf4j
      datasource: 
        master: 
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.98.113.109:8732/cheetah_music?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;useSSL=false
server:
  port: 9099
mybatis-plus:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  typeEnumsPackage: com.cheetah.dubbo.base.enums
dubbo: 
    application:
      name: provider
    config:
      multiple: true
    protocols: 
      dubbo: 
       port: 20880
       name: dubbo
      rest: 
       server: tomcat
       contextpath: /rest
       port: 8088
       name: rest
    registry: 
      address: zookeeper://127.0.0.1:2181
    provider: 
     timeout: 1000    