server: 
  port: 9098
  servlet:
    context-path: /cheetah/api
dubbo: 
    application:
      name: consumer-client
    protocol:
      name: dubbo
      port: 20880
    registry: 
      address: zookeeper://47.98.113.109:2181
    consumer: 
      timeout: 5000